#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// jane is a value multiple by gyro degree
#define jane 3

void moveS(int speed){
		int degree = getGyroDegrees(gyroSensor);
		motor[leftMotor] = speed + (-1 * degree * jane);
		motor[rightMotor] = speed + (degree * jane);
}

void turn90left(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(100);
	int degree = getGyroDegrees(gyroSensor);
	while(degree != -90){
		degree = getGyroDegrees(gyroSensor);
		motor[leftMotor] = -1 * (degree + 90)/3+2;
		motor[rightMotor] = (degree + 90)/3+2;
	}
	//wait1Msec(500);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(500);
	resetGyro(gyroSensor);
}

void turn90leftV2(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(100);
	//resetGyro(gyroSensor);
	int a = 1;
	int degree = getGyroDegrees(gyroSensor);
	while(degree > -90){
		degree = getGyroDegrees(gyroSensor);
		motor[leftMotor] = -10 * a;
		motor[rightMotor] = 10 * a;
	}
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(200);
	while(degree < -90){
		degree = getGyroDegrees(gyroSensor);
		motor[leftMotor] = 10;
		motor[rightMotor] = -10;
	}



		motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(100);
	resetGyro(gyroSensor);

}

void turn90leftV3(){

	resetGyro(gyroSensor);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(200);
	int degree = getGyroDegrees(gyroSensor);
	while(degree > -90){
		degree = getGyroDegrees(gyroSensor);
		motor[leftMotor] = -2;
		motor[rightMotor] = 2;
	}


	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(200);
	resetGyro(gyroSensor);

}


task main()
{
	resetGyro(gyroSensor);
	wait1Msec(500);

	while(1){
		//moveS(40);
	wait1Msec(500);
		turn90leftV3();
	}

}
