#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/
// jane is a value multiple by gyro degree
#define jane 3
#define blockDistance 625
#define baseSpeed 40
void moveS(int basespeed,int target){
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(100);

		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);
		resetGyro(gyroSensor);
		wait1Msec(100);

		setMotorTarget(leftMotor,target,0);
		setMotorTarget(rightMotor,target,0);

		while(getMotorEncoder(leftMotor) <= target && getMotorEncoder(rightMotor) <= target) {
			int degree = getGyroDegrees(gyroSensor);
			motor[leftMotor] = basespeed + (-1 * degree * jane);
			motor[rightMotor] = basespeed + (degree * jane)+3;
		}

		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}


void turn90leftV3(){

	resetGyro(gyroSensor);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(200);
	int degree = getGyroDegrees(gyroSensor);
	while(degree > -90){
		degree = getGyroDegrees(gyroSensor);
		motor[leftMotor] = -8;
		motor[rightMotor] =8;
	}


	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(500);
}

void moveS_D90(int basespeed,int target){
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(100);

		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);
		wait1Msec(100);

		setMotorTarget(leftMotor,target,0);
		setMotorTarget(rightMotor,target,0);

		while(getMotorEncoder(leftMotor) <= target && getMotorEncoder(rightMotor) <= target) {
			int degree = getGyroDegrees(gyroSensor);
			motor[leftMotor] = basespeed + (-1 * (degree+90) * jane);
			motor[rightMotor] = basespeed + ((degree+90) * jane)+3;
		}

		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}

task main()
{
	resetGyro(gyroSensor);
	wait1Msec(500);
	moveS(baseSpeed,blockDistance*9);
	turn90leftV3();
	moveS_D90(baseSpeed,blockDistance*9-20);
	turn90leftV3();

	moveS_D90(baseSpeed,blockDistance*7);
	turn90leftV3();
	moveS_D90(baseSpeed,blockDistance*7);
	turn90leftV3();

	moveS_D90(baseSpeed,blockDistance*5);
	turn90leftV3();
	moveS_D90(baseSpeed,blockDistance*5);
	turn90leftV3();

	moveS_D90(baseSpeed,blockDistance*3);
	turn90leftV3();
	moveS_D90(baseSpeed,blockDistance*3);
	turn90leftV3();

	moveS_D90(baseSpeed,blockDistance*1);
	turn90leftV3();
	moveS_D90(baseSpeed,blockDistance*1);

	motor[leftMotor] = 80;
	motor[rightMotor] = -80;
	wait1Msec(1000);

}
