#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define jane 3
#define blockDistance 625
#define baseSpeed 35

void stopMotor(){
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
}

void turn90leftV3(){
	stopMotor();
	wait1Msec(200);
	resetGyro(gyroSensor);
	wait1Msec(200);
	setMotorSpeed(leftMotor,-10);
	setMotorSpeed(rightMotor,10);
	while(getGyroDegrees(gyroSensor) > -88){}
	stopMotor();
	wait1Msec(1000);
}

void moveS(int basespeed,int target){
		resetGyro(gyroSensor);
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(100);

		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);
		resetGyro(gyroSensor);
		wait1Msec(100);

		setMotorTarget(leftMotor,target,0);
		setMotorTarget(rightMotor,target,0);

		while(getMotorEncoder(leftMotor) <= target && getMotorEncoder(rightMotor) <= target) {
			int degree = getGyroDegrees(gyroSensor);
			motor[leftMotor] = basespeed + (-1 * degree * jane);
			motor[rightMotor] = basespeed + (degree * jane)+2;
		}

		stopMotor();
		wait1Msec(1000);
}

void moveS_D90(int basespeed,int target){
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(100);

		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);
		wait1Msec(100);

		setMotorTarget(leftMotor,target,0);
		setMotorTarget(rightMotor,target,0);

		while(getMotorEncoder(leftMotor) <= target && getMotorEncoder(rightMotor) <= target) {
			int degree = getGyroDegrees(gyroSensor);
			motor[leftMotor] = basespeed + (-1 * (degree+90) * jane);
			motor[rightMotor] = basespeed + ((degree+90) * jane);
		}

		stopMotor();
		wait1Msec(1000);
}

task main()
{
resetGyro(gyroSensor);
	wait1Msec(500);
	/*moveS(baseSpeed,blockDistance*9+20);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*9-20);
	turn90leftV3();

	moveS(baseSpeed,blockDistance*7-20);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*7);
	turn90leftV3();

	moveS(baseSpeed,blockDistance*5);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*5);
	turn90leftV3();

	moveS(baseSpeed,blockDistance*3);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*3);
	turn90leftV3();

	moveS(baseSpeed,blockDistance*1);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*1);*/

	moveS(baseSpeed,620*15);

	motor[leftMotor] = 80;
	motor[rightMotor] = -80;
	wait1Msec(1000);
}
