#pragma config(Sensor, S1,     frontSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     rightTrack,     sensorEV3_Color)
#pragma config(Sensor, S3,     colorCheck,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     leftTrack,      sensorEV3_Color)
#pragma config(Motor,  motorA,          grabMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//constant area
#define Kp 0.18
#define Kd 0.25
#define Kc 0.001

#define target 600
#define baseSpeed 40
#define turnSpeed 15
#define orangeBox 7
#define innerLineValue 10
#define outerLineValue 5
#define moveColorSensorDiff 2
#define whiteTreshold 10
#define blackTreshold 2
#define baseDistance 15


// describe function
static void turnleft(void);
static void moveStright(void);
static void stopMoving(void);
static void movereverse(int targetDistance);
static char moveStrightTarget(int backward);
static void grab();
static void releaseGrab(void);
static void calDirection(char dirFunc);
static void calPosition(void);
static void moveAgain(void);
static void moveAgainEncoder(void);

//global variabal
int frontColorSensor = 0;
int direction = 8;
int position[2] = {8,8};
char resultAfterMove = 'x';
bool isDone = false ;

task main()
{
	   while(1){

	  /* frontColorSensor = SensorValue(colorCheck);
	   moveStright();
	   if(frontColorSensor >= orangeBox){
	      stopMoving();
	      releaseGrab();
	      moveStrightTarget(80);
	      grab(isGrab);
	      movereverse(500);
	   } */

     moveStrightTarget(1);
     moveAgainEncoder();
     //turnleft();

   }
}

char moveStrightTarget(int backward){

    int rightSensor = getColorReflected(rightTrack);
	  int leftSensor  = getColorReflected(leftTrack);
	  int frontSensorValue = getUSDistance(frontSensor);
	  float error = rightSensor - leftSensor;
    float motorSpeed = baseSpeed;
    float lastError = error;
    char varRet = 'x';
    isDone = false ;

    while(!isDone){

       rightSensor = getColorReflected(rightTrack);
	     leftSensor = getColorReflected(leftTrack);
	     frontSensorValue = getUSDistance(frontSensor);
	     error = (rightSensor - leftSensor)+Kc;
       lastError = error;
       motorSpeed = Kp * error + Kd * (error - lastError);

       motor[leftMotor]  = backward*baseSpeed - motorSpeed;
       motor[rightMotor] = backward*baseSpeed + motorSpeed;

       if(frontSensorValue <= baseDistance ){
            int colorSensor = SensorValue(colorCheck);
            if(colorSensor >= orangeBox ){
            	varRet = 'o';
            }
            else {
            	varRet = 'b';
            }
            isDone = true;
       }

       if(rightSensor <= 2 && leftSensor <= 2){
          isDone = true;
          varRet = 'w';
       }


    }
    stopMoving();
    return varRet;

}
void stopMoving(){

	  motor[leftMotor] = 0 ;
	  motor[rightMotor] = 0 ;
	  delay(200);
}
void moveAgain(){

	  int rightSensor = getColorReflected(rightTrack);
	  int leftSensor = getColorReflected(leftTrack);
	  float error = rightSensor - leftSensor;
    float motorSpeed = baseSpeed;
    float lastError = error;
	  while(rightSensor <= 10 && leftSensor <= 10){

       rightSensor = getColorReflected(rightTrack);
	     leftSensor = getColorReflected(leftTrack);
	     error = rightSensor - leftSensor;
       lastError = error;
       motorSpeed = Kp * error + Kd * (error - lastError);
       motor[leftMotor]  = baseSpeed - motorSpeed;
       motor[rightMotor] = baseSpeed + motorSpeed;

     }
     stopMoving();

}
void moveAgainEncoder(){
	   resetMotorEncoder(leftMotor);
	   resetMotorEncoder(rightMotor);
	   int leftdist = getMotorEncoder(leftMotor);
	   int rightdist = getMotorEncoder(rightMotor);
	   while(leftdist <= 100 && rightdist <= 100){

	     leftdist = getMotorEncoder(leftMotor);
	     rightdist = getMotorEncoder(rightMotor);
	     motor[leftMotor]  = baseSpeed ;
       motor[rightMotor] = baseSpeed ;

	   }
	   stopMoving();
}
void movereverse(int targetDistance){


}

void turnleft(){

	  int rightSensor = getColorReflected(rightTrack);
	  int leftSensor = getColorReflected(leftTrack);

	      rightSensor = getColorReflected(rightTrack);
	      leftSensor  = getColorReflected(leftTrack);
	  	  int diff = rightSensor - leftSensor;
	  	  while(leftSensor >= blackTreshold ){

	          leftSensor = getColorReflected(leftTrack);

	  	  	  motor[rightMotor] = -turnSpeed;
	  	  	  motor[leftMotor] =  turnSpeed;

	  	  }
	  	  stopMoving();

	  	  while(diff >= 2 || leftSensor <= 8 || rightSensor <= 8){

	  	      rightSensor = getColorReflected(rightTrack);
	          leftSensor = getColorReflected(leftTrack);

	  	      motor[rightMotor] = -turnSpeed;
	  	  	  motor[leftMotor]  =  turnSpeed;

	  	  }

	  calDirection('l');
	  stopMoving();
}

void grab(){


       moveMotorTarget(grabMotor,280,100);
       delay(1000);
       resetMotorEncoder(grabMotor);
}

void releaseGrab(){


       moveMotorTarget(grabMotor,-280,-100);
       delay(1000);
       resetMotorEncoder(grabMotor);

}

void calDirection(char dirFunc)
{
	  if(dirFunc == 'l'){
	  	 switch(direction){
	  	    case 8 :
	  	       direction = 1;
	  	       break;
	  	    case 4 :
	  	       direction = 8;
	  	       break;
	  	    case 2 :
	  	       direction = 4;
	  	       break;
	  	    case 1 :
	  	       direction = 2;
	  	       break;
	  	 }
	  }
	  else if(dirFunc == 'r'){
	  	 switch(direction){
	  	    case 8 :
	  	       direction = 4;
	  	       break;
	  	    case 4 :
	  	       direction = 2;
	  	       break;
	  	    case 2 :
	  	       direction = 1;
	  	       break;
	  	    case 1 :
	  	       direction = 8;
	  	       break;
	  	 }
	  }
}

void calPosition(){
	//draw current position
	 switch(direction){
	   case 1 :
	      position[1]--;
	      break;
	   case 2 :
	      position[0]++;
	      break;
	   case 4 :
	      position[1]++;
	      break;
	   case 8 :
	      position[0]--;
	      break;
   }
}
